version: "3.4"

services:

  webm-perpetual:
      image: vsblty.azurecr.io/vsblty/videowebmstreaming:1.0.0
      container_name: webm-perpetual
      privileged: true
      volumes:
        - Videos:/opt/Vsblty/videos
        - ConvertedVideos:/opt/Vsblty/convertedVideos
        - ProcessedVideos:/opt/Vsblty/processedVideos
        - ~/.Xauthority:/root/.Xauthority
        - /tmp/.X11-unix/:/tmp/.X11-unix/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "80:80"
        - "443:443"

volumes:
    Videos:
    ConvertedVideos:
    ProcessedVideos: